package ca.mcgill.ecse321.artgallery.model;


public enum ArtworkType{
	
	CERAMIC,
	DRAWING,
	ACRYLIC_PAINTING,
	INK_PAINTING,
	OIL_PAINTING,
	WATER_COLOUR_PAINTING,
	PASTEL_PAINTING,
	ENCAUSTIC_PAINTING,
	FRESCO_PAINTING,
	GOUACHE_PAINTING,
	ENAMEL_PAINTING,
	SPRAY_PAINT,
	DIGITAL_PAINTING,
	STONE_SCULPTURE,
	METAL_SCULPTURE,
	GLASS_SCULPTURE,
	WOOD_SCULPTURE,
	POTERY,
	PHOTOGRAPHY,
	

}
